spring.application.name=ticket

server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/ticket}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.example.ticket=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect