spring.application.name=bff
server.port=8080

auth.service.base-url=${AUTH_SERVICE_URL:http://localhost:7778}

security.jwt.secret=$&miSercreto.SuperSeguro!1988
security.jwt.expiration-hours=24

ticket.service.url=${TICKET_SERVICE_URL:http://localhost:8082}
cliente.service.url=${CLIENTE_SERVICE_URL:http://localhost:8083}
tecnico.service.url=${TECNICO_SERVICE_URL:http://localhost:8081}