spring.application.name=gateway
server.port=8000

auth.service.url=${AUTH_SERVICE_URL:http://localhost:7778}
bff.service.url=${BFF_SERVICE_URL:http://localhost:8080}

management.endpoints.web.exposure.include=health,info

logging.level.root=INFO
logging.level.com.serviciotecnico.gateway=INFO