spring.application.name=diagnostico
server.port=8086

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5439/diagnostico_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=${JWT_SECRET:dev-only-secret-change-me}